settings:
  path: /settings-of
  controller: App\Controller\SettingsController::show
  methods: GET

settings_save:
  path: /settings-of/save
  controller: App\Controller\SettingsController::save
  methods: POST
