services:

  _defaults:

    autowire: true
    autoconfigure: true

  Creatortsv\ServicesConfiguratorBundle\Services\:
    resource: '../src/Services/*'

  Creatortsv\ServicesConfiguratorBundle\Services\ServiceInterface:
        factory: '@?Creatortsv\ServicesConfiguratorBundle\Services\ServiceFactory'
        arguments: 
          - '@Symfony\Component\HttpFoundation\RequestStack'
          - '@service_container'